replace with the number of runs you want
replace with the max displacement you want to run
replace with number of prossesors you want to use for sim
replace with gmsh.exe path (if in windows PATH var, you may be able to just put gmsh)
replace with elmergrid.exe path (if in windows PATH var, you may be able to just put elmergrid)
replace with elmersolver.exe path (if in windows PATH var, you may be able to just put elmersolver)